# Generated by Django 5.1.6 on 2025-02-14 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unique_id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=36, unique=True
                    ),
                ),
                ("encoding", models.BinaryField()),
                ("image", models.ImageField(upload_to="faces/")),
            ],
        ),
    ]
